### ISSUE TITLE
danil, plz

### ISSUE THREAD

**Issue by Caparow** [Caparow/MoneyAccounter#13]
pochini ebanui bag s ebanum integerom v pole vvoda

**Comment by danyfedorov** [comment]
sho za bag, alle

**Comment by Caparow** [comment]
esli vvesti ne cuffru v pole znacheniia pri dobavleni to PEZDA

**Comment by danyfedorov** [comment]
# PONIAL

**Comment by Caparow** [comment]
# C P A C N B O

**Comment by danyfedorov** [comment]
# `S D E L A V`

**Comment by Caparow** [comment]
# K P A C U B O
